### ISSUE TITLE
Only one validator is created

### ISSUE THREAD

**Issue by liorzilp** [dymensionxyz/infrastructure#22]
## Overview
The setup should bring-up 2 validators for the hub, but only validator-2 exists:
```
bash-5.1#dymd q staking validators --node tcp://localhost:26657
pagination:
  next_key: null
  total: "0"
validators:
- commission:
    commission_rates:
      max_change_rate: "0.010000000000000000"
      max_rate: "0.200000000000000000"
      rate: "0.100000000000000000"
    update_time: "2023-01-24T12:08:31.215013630Z"
  consensus_pubkey:
    '@type': /cosmos.crypto.ed25519.PubKey
    key: etjlYHuoBaCDs10rgLQKWYV0uvXnppKmcWoN742t3LU=
  delegator_shares: "100000000.000000000000000000"
  description:
    details: ""
    identity: ""
    moniker: hub-validator-2
    security_contact: ""
    website: ""
  jailed: false
  min_self_delegation: "1"
  operator_address: dymvaloper1a6r7uf0jeer2l4fclg0ylmegn9fyj80kgq9877
  status: BOND_STATUS_BONDED
  tokens: "100000000"
  unbonding_height: "0"
  unbonding_time: "1970-01-01T00:00:00Z"
```

## Problem
The gentx missing CreateValidator transaction for the first validator.

### Solution
In the hub container image add the additional validator to `/home/shared/gentx/genesis.json` the same as done for the first one:

     "genutil": {
      "gen_txs": [
        {
          "body": {
            "messages": [
              {
                "@type": "/cosmos.staking.v1beta1.MsgCreateValidator",
