### ISSUE TITLE
Validator version mismatch

### ISSUE THREAD

**Issue by liorzilp** [dymensionxyz/infrastructure#36]
## Overview
In `docker-compose.yml` we specify the image versions.
All validators must run the same version.

## Bug
The images of the validator are different so the validators code version is different as well.
From `docker-compose.yml`:

```
  hub-validator-1:
    container_name: hub-validator-1
    image: ghcr.io/dymensionxyz/dymension:latest

  hub-validator-2:
    container_name: hub-validator-2
    image: dymensionxyz/dymension

```
